### ISSUE TITLE
Allow playbooks to define own configuration files

### ISSUE THREAD

**Issue by hnk** [alvistack/ansible-role-jira#4]
I am using your role to configure our jira server. Sadly we are running a slightly different configuration: Jira is configured to run behind a proxy server.

Thus we have to modify server.xml to support that.

I'd like to be able to define a custom template location, as is implemented in the excellent [geerlingguy/ansible-role-gitlab](https://github.com/geerlingguy/ansible-role-gitlab/issues/16) via [this MR](https://github.com/geerlingguy/ansible-role-gitlab/pull/89).

Would you be open to a similar solution (also for your confluence role).

Currently we have an extra task that deploy the custom template after your role runs, thus always recreating the templated files twice (once for the role, once for our template) and restarting jira, even when nothing changed.

**Comment by mttjohnson** [comment]
@hnk I've used this role with a Jira server that is running behind a load balancer. It's possible you just need to define some variables when calling the role, like this:

```
    - role: classyllama.jira
      jira_version: "8.4.1"
      _jira_download:
        # https://www.atlassian.com/software/jira/download
        8.4.1:
          url: "https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.4.1.tar.gz"
          dest: "/var/cache/ansible/atlassian-jira-software-8.4.1.tar.gz"
          # sha1sum atlassian-jira-software-8.4.1.tar.gz
          checksum: "sha1:33dbd00107c913f90886b948d4a34446955aa160"
      jira_jvm_minimum_memory: "384m"
      jira_jvm_maximum_memory: "3072m"
      jira_catalina_connector_proxyname: jiralb.example.com
      jira_catalina_connector_proxyport: 443
      jira_catalina_connector_scheme: "https"
      jira_catalina_connector_secure: "true"
```

I have a few more things in that example above, but the main thing you're likely concerned with is:
```
    - role: classyllama.jira
      jira_catalina_connector_proxyname: jiralb.example.com
      jira_catalina_connector_proxyport: 443
      jira_catalina_connector_scheme: "https"
      jira_catalina_connector_secure: "true"
```

Those variables define values placed in the /opt/atlassian/jira/bin/setenv.sh script that starts up Jira, and that script sets some variables inside the Java application. You may noticed some references to the Java variables in the server.xml template file, and they look like this `${catalina.connector.proxyName}`, `${catalina.connector.proxyPort}`, `${catalina.connector.scheme}`, and `${catalina.connector.secure}`.
